name: Static CI/CD

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]


  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP_ADDRESS }}
        username: ${{ secrets.ADMIN_USERNAME }}
        key: ${{ secrets.key }}
        script: |
          cd /var/www/html/weaher
          git pull origin master
